config/routes.rb
Gifster::Application.routes.draw do

  resources :friendships
  resources :users do
    resources :conversations
    resources :friends
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :participants
  has_many :users, through: :participants
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :participants
  has_many :conversations, through: :participants

  has_many :friendships
  has_many :friends, through: :friendships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  def index
    user = User.find(params[:user_id])
    @conversations = user.conversations

    respond_to do |format|
      format.html {
        @conversations_json = @conversations.map {|convo| ConversationSerializer.new(convo).serializable_hash}
        @user_id = user.id
      }
      format.json { render json: @conversations, root: false, each_serializer: ConversationSerializer }
    end
  end

  # GET /conversations/1
  def show
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  def create
    @conversation = Conversation.new(conversation_params)

    if @conversation.save
      redirect_to @conversation, notice: 'Conversation was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /conversations/1
  def update
    if @conversation.update(conversation_params)
      redirect_to @conversation, notice: 'Conversation was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /conversations/1
  def destroy
    @conversation.destroy
    redirect_to conversations_url, notice: 'Conversation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def conversation_params
      params[:conversation]
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_user

  def index
    @friends = @user.friends

    respond_to do |format|
      format.html {
        @friends_json = @friends.to_json
        @user_id = @user.id
      }
      format.json { render json: @friends, root: false}
    end
  end

  def create
    new_friend = User.find_by_email(params[:email])

    respond_to do |format|
      if @user && new_friend
        @user.friends << new_friend
        format.html { redirect_to user_friends_path(@user), notice: 'Friend Successfully Added' }
        format.json { render json: new_friend.to_json, root: false }
      else
        format.html { render action: 'new' }
        format.json { render json: {error: "No user exists with that email"}, status: 404}
      end
    end
  end

  def destroy
    respond_to do |format|
      Friendship.where(user_id: @user.id, friend_id: params[:id]).first.destroy
      format.html { redirect_to user_friends(@user), notice: 'Friendship Ended' }
      format.json { render json: true}
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  def create
    @friendship = Friendship.new(friendship_params)

    if @friendship.save
      redirect_to @friendship, notice: 'Friendship was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /friendships/1
  def update
    if @friendship.update(friendship_params)
      redirect_to @friendship, notice: 'Friendship was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /friendships/1
  def destroy
    @friendship.destroy
    redirect_to friendships_url, notice: 'Friendship was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :create, :destroy)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all

    respond_to do |format|
      format.html {
        @users_json = @users.map {|user| UserSerializer.new(user).serializable_hash}
        @urls = {
          users: users_path
        }
      }
      format.json { render json: @users, root: false, each_serializer: UserSerializer }
    end
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, root: false }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render json: @user, root: false}
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /users/1
  def destroy
    respond_to do |format|
      @user.destroy
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { render json: true}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/_form.html.erb
<%= form_for(@conversation) do |f| %>
  <% if @conversation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited this conversation from being saved:</h2>

      <ul>
      <% @conversation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversations/edit.html.erb
<h1>Editing conversation</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<div ng-app="Gifster" ng-controller="ConversationsController" ng-init="conversations=<%=@conversations_json.to_json%> ;user_id=<%=@user_id.to_json%>">
  <div class="row">
    <div class="col-md-6">
      <h2>Start A New Conversation</h2>
      <form ng-submit="save()">
        <div class="form-group">
          <label>Add Friend</label>
          <input type="text" class="form-control" ng-model="friend" />
        </div>
        <button class="btn btn-primary">
          Save
        </button>
      </form>


      <h1>Conversations</h1>
      <ul>
        <li ng-repeat="conversation in conversations">
          Last Activity {{conversation.updated_at}}
          <div class="btn btn-default" ng-click="delete(conversation, $index)">
            <%= fa_icon "trash-o" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/conversations/new.html.erb
<h1>New conversation</h1>

<%= render 'form' %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_conversation_path(@conversation) %> |
<%= link_to 'Back', conversations_path %>

app/views/friends/index.html.erb
<div ng-app="Gifster" ng-controller="FriendsController" ng-init="friends=<%= @friends_json %>; user_id=<%= @user_id %>">
  <div class="row">
    <div class="col-md-6">
      <h2>Add a Friend</h2>
      <form ng-submit="save()">
        <div class="form-group">
          <label>Email</label>
          <input type="text" class="form-control" ng-model="friend.email" />
        </div>
        <button class="btn btn-primary">
          Add
        </button>
      </form>


      <h1>Friend's List</h1>
      <ul>
        <li ng-repeat="friend in friends">
          {{friend.first_name}} {{friend.last_name}}
          <a ng-click="delete(friend, $index)">unfriend</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :create %><br>
    <%= f.text_field :create %>
  </div>
  <div class="field">
    <%= f.label :destroy %><br>
    <%= f.text_field :destroy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Create</th>
      <th>Destroy</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.create %></td>
        <td><%= friendship.destroy %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Create:</strong>
  <%= @friendship.create %>
</p>

<p>
  <strong>Destroy:</strong>
  <%= @friendship.destroy %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/application.html.erb
<!DOCTYPEhtml>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gifster" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-inverse">
      <div class="container">
        <a class="navbar-brand" href="#">Gifster</a>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div ng-app="Gifster" ng-controller="UsersController" ng-init="getUsers()">
  <div class="row">
    <div class="col-md-6">
      <h2>{{formHeader}}</h2>
      <form ng-submit="save()">
        <div class="form-group">
          <label>First Name</label>
          <input type="text" class="form-control" ng-model="user.first_name" />
        </div>
        <div class="form-group">
          <label>Last Name</label>
          <input type="text" class="form-control" ng-model="user.last_name" />
        </div>
        <div class="form-group">
          <label>Email</label>
          <input type="text" class="form-control" ng-model="user.email" />
        </div>
        <button class="btn btn-primary">
          Save
        </button>
      </form>

      <h1>Users</h1>
      <ul>
        <li ng-repeat="user in users">
          {{ user.first_name }} {{ user.last_name }} ( {{user.email}} )
          <div class="btn btn-default" ng-click="edit(user, $index)">
            <%= fa_icon "pencil" %>
          </div>
          <div class="btn btn-default" ng-click="delete(user, $index)">
            <%= fa_icon "trash-o" %>
          </div>
          <a href="/users/{{user.id}}/conversations">convos</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>